#!/usr/bin/env bash

THISDIR=$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

# Remember to backup existing config files.

if [ "$(uname)" == "Darwin" ]; then
    sudo ln -si "${THISDIR}/bashrc" /etc/bashrc
elif [ "$(uname)" == "Linux" ]; then
    sudo ln -si "${THISDIR}/bashrc" /etc/bash.bashrc
fi
